server:
  type: default
  maxThreads: 100
  minThreads: 100
  applicationConnectors:
    - type: http
      port: 14041
      acceptorThreads: 8
      selectorThreads: 16
  adminConnectors:
    - type: http
      port: 14042
  requestLog:
    timeZone: IST
    appenders:
      - type: file
        currentLogFilename: ./logs/access.log
        threshold: INFO
        archive: true
        archivedLogFilenamePattern: ./logs/access-%d{yyyy-MM-dd-HH}.log.gz
        archivedFileCount: 50
        timeZone: IST